export const events = [
  {
    title: "React Universe Conf 2025",
    slug: "react-universe-conf-2025",
    image: "/images/event1.png",
    location: "San Francisco, CA",
    date: "August 15, 2025",
    time: "9:00 AM PST",
  },
  {
    title: "Next.js Conf",
    slug: "nextjs-conf",
    image: "/images/event2.png",
    location: "Online",
    date: "October 24, 2025",
    time: "10:00 AM PST",
  },
  {
    title: "AI Engineer Summit",
    slug: "ai-engineer-summit",
    image: "/images/event3.png",
    location: "New York, NY",
    date: "November 12, 2025",
    time: "8:30 AM EST",
  },
  {
    title: "JS World Conference",
    slug: "js-world-conference",
    image: "/images/event4.png",
    location: "Amsterdam, Netherlands",
    date: "February 28, 2026",
    time: "9:00 AM CET",
  },
  {
    title: "AWS re:Invent",
    slug: "aws-reinvent",
    image: "/images/event5.png",
    location: "Las Vegas, NV",
    date: "December 2, 2025",
    time: "8:00 AM PST",
  },
  {
    title: "Google I/O 2026",
    slug: "google-io-2026",
    image: "/images/event6.png",
    location: "Mountain View, CA",
    date: "May 14, 2026",
    time: "10:00 AM PST",
  },
];
